name: Build and publish to docker hub

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   # Add support for more platforms with QEMU (optional)
      #   # https://github.com/docker/setup-qemu-action
      #   uses: docker/setup-qemu-action@v3
      - name: Set the version
        shell: bash
        if: env.CADDY_VERSION == ''
        run: |
          echo "CADDY_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Build and push to docker hub
        run: |
          echo "Build caddy version: ${{ env.CADDY_VERSION }}"
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker buildx build \
            --build-arg CADDY_VERSION=${{ env.CADDY_VERSION }} \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag ${{ secrets.DOCKER_USERNAME }}/caddy-dav:${{ env.CADDY_VERSION }} \
            --push .
      #
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/caddy-dav
